### ISSUE TITLE
macOS sierra builds of the `.app` don't work with 10.10

### ISSUE THREAD

**Issue by Austcool-Walker** [minecraft-linux/mcpelauncher-manifest#20]
dyld: Symbol not found: _clock_getres
  Referenced from: /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client
Process exited with unexpected exit code: 5

In the future I would like to see the program work with older OS X

**Comment by Austcool-Walker** [comment]
also why not just bundle that dependency in the app?
